import { chromium } from 'playwright';
const [url, out, w = '1440', h = '1200', full = '1'] = process.argv.slice(2);
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: +w, height: +h }, deviceScaleFactor: 1 });
const errs = [];
p.on('console', (m) => { if (m.type() === 'error') errs.push(m.text()); });
p.on('pageerror', (e) => errs.push(String(e)));
await p.goto(url, { waitUntil: 'networkidle' });
await p.waitForTimeout(900);
await p.screenshot({ path: out, fullPage: full === '1' });
if (errs.length) console.log('CONSOLE ERRORS:\n' + errs.join('\n'));
await b.close();
